name: Swift Package
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - '.github/**' # Ignore all files under '.github'
      - '!.github/workflows/swift-package.yml' # Except for this workflow
      - '.gitignore'
      - '.swiftlint.yml'
      - 'Documentation/**'
      - 'LICENSE'
      - 'README.md'
      - 'SRDTestUtilities.podspec'

jobs:
  build:
    name: Build
    runs-on: macOS-11
    env:
      LOGSDIR: /tmp/.srdtestutilities.swiftpm/Logs

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build
      run: |
        swift --version | tee "$LOGSDIR/Build.log"
        swift build --verbose | tee -a "$LOGSDIR/Build.log"

  test:
    name: Test
    runs-on: macOS-11
    needs: build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Test
      run: |
        swift test --verbose --enable-code-coverage | tee "$LOGSDIR/Test.log"

    - name: Generate Code Coverage File
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: |
        xcrun llvm-cov export --format=lcov --instr-profile=".build/debug/codecov/default.profdata" ".build/debug/SRDTestUtilitiesPackageTests.xctest/Contents/MacOS/SRDTestUtilitiesPackageTests" > "./codecov.lcov"

    - name: Upload Code Coverage
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./codecov.lcov
        verbose: true
