name: Upload Assets
on:
  release:
    types: [published]

jobs:
  build:
    name: Upload XCFramework Assets
    runs-on: macOS-11
    env:
      TMPDIR: /tmp/.srdtestutilities.assets-xcframework.build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Environment
      run: |
        mkdir -p "${TMPDIR}/Output"
        mkdir -p "${TMPDIR}/Logs"

    - name: Build
      run: |
        ./scripts/xcframework.sh --build-dir "${TMPDIR}" --output "${TMPDIR}/Output/SRDTestUtilities.xcframework" -- RUN_DOCUMENTATION_COMPILER=NO SKIP_SWIFTLINT=YES

    - name: Create Zip
      run: |
        cd "${TMPDIR}/Output"
        zip -rX SRDTestUtilities.xcframework.zip SRDTestUtilities.xcframework 2>&1 | tee "${TMPDIR}/Logs/Zip.log"

    - name: Upload Zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.TMPDIR }}/Output/SRDTestUtilities.xcframework.zip
        asset_name: SRDTestUtilities.xcframework.zip
        asset_content_type: application/zip

    - name: Create Tar
      run: |
        cd "${TMPDIR}/Output"
        tar -zcvf SRDTestUtilities.xcframework.tar.gz SRDTestUtilities.xcframework 2>&1 | tee "${TMPDIR}/Logs/Tar.log"

    - name: Upload Tar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.TMPDIR }}/Output/SRDTestUtilities.xcframework.tar.gz
        asset_name: SRDTestUtilities.xcframework.tar.gz
        asset_content_type: application/gzip

    - name: Upload Logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: XCFrameworkLogs
        path: ${{ env.TMPDIR }}/Logs/*.log



    name: Upload Documentation Assets
    runs-on: macOS-11
    env:
      TMPDIR: /tmp/.srdtestutilities.assets-documentation.build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Environment
      run: |
        mkdir -p "${TMPDIR}/Output"
        mkdir -p "${TMPDIR}/Logs"

    - name: Build
      run: |
        xcodebuild docbuild -project "SRDTestUtilities.xcodeproj" -scheme "SRDTestUtilities" -destination "generic/platform=iOS" -derivedDataPath "${TMPDIR}/.docbuild" 2>&1 | tee "${TMPDIR}/Logs/Build.log"

        DOCC_ARCHIVE="$(find "${TMPDIR}/.docbuild" -type d -name "SRDTestUtilities.doccarchive")"
        mv "${DOCC_ARCHIVE%/}" "${TMPDIR}/Output/SRDTestUtilities.doccarchive"

    - name: Create Zip
      run: |
        cd "${TMPDIR}/Output"
        zip -rX SRDTestUtilities.doccarchive.zip SRDTestUtilities.doccarchive 2>&1 | tee "${TMPDIR}/Logs/Zip.log"

    - name: Upload Zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.TMPDIR }}/Output/SRDTestUtilities.doccarchive.zip
        asset_name: SRDTestUtilities.doccarchive.zip
        asset_content_type: application/zip

    - name: Create Tar
      run: |
        cd "${TMPDIR}/Output"
        tar -zcvf SRDTestUtilities.doccarchive.tar.gz SRDTestUtilities.doccarchive 2>&1 | tee "${TMPDIR}/Logs/Tar.log"

    - name: Upload Tar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.TMPDIR }}/Output/SRDTestUtilities.doccarchive.tar.gz
        asset_name: SRDTestUtilities.doccarchive.tar.gz
        asset_content_type: application/gzip

    - name: Upload Logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: DocumentationLogs
        path: ${{ env.TMPDIR }}/Logs/*.log
